apiVersion: v1
kind: Pod
metadata:
  name: scaling
  labels:
    app: scaling
spec:
  serviceAccountName: admin-user
  automountServiceAccountToken: true
  containers:
  - env:
    - name: PYFAAS_PREDICTION_SERVER
      value: "http://predictionsvc:8080"
    - name: PYFAAS_DEPLOYMENT
      value: hello
    name: worker
    image: matei10/pyfaas_scale:10
    imagePullPolicy: Always
