apiVersion: v1
kind: Pod
metadata:
  name: predict
  labels:
    app: predict
spec:
  containers:
  - name: prediction-worker
    image: matei10/pyfaas_predict:9
    imagePullPolicy: Always
    env:
    - name: RESP
      value: "80"
---
kind: Service
apiVersion: v1
metadata:
  name: predictionsvc
spec:
  selector:
    app: predict
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
